### PR TITLE
Assert helpers to reduce repetition

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by JohanLarsson** [comment]
Maybe we should leave static API asserts for one valid.cs and fix.cs?
It will be inconsistent but I'm thinking it can be good to keep a couple of real world tests for that API to prevent regressions.

**Comment by JohanLarsson** [comment]
Looks nice!

**Comment by jnm2** [comment]
Sure! Does one recommend itself to you, or should I choose the first in the list?

**Comment by JohanLarsson** [comment]
First pair valid.cs & fix.cs in the list sounds fine.

**Pull request merged**
